# Generated by Django 5.2 on 2025-04-20 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='name',
            field=models.CharField(default='Unnamed Product', max_length=100),
        ),
    ]
